version: '3.2'

services:
    python:
        image: kanameg/kindle_python:1.0
        build: ./python
        container_name: 'kindle_python'
        expose: 
            - 8880
        stdin_open: true
        tty: true
        working_dir: '/tmp/work'
        volumes:
            - ../python/src:/tmp/work

